### ISSUE TITLE
wallet throw new Error(data.message)

### ISSUE THREAD

**Issue by shop271** [HathorNetwork/hathor-wallet-headless#134]
wallet: '0.9.1', version: 'v16.13.0'
htr：'0.45.0'

```
/data2/.htr/minming_wallet/hathor-wallet-headless/node_modules/@hathor/wallet-lib/lib/wallet.js:2641
      throw new Error(data.message);
      ^

Error: Reached maximum number of subscribed addresses without output (100).
    at WS.onSubscribeAddress (/data2/.htr/minming_wallet/hathor-wallet-headless/node_modules/@hathor/wallet-lib/lib/wallet.js:2641:13)
    at WS.emit (node:events:390:28)
    at WS.emit (node:domain:475:12)
    at WS.onMessage (/data2/.htr/minming_wallet/hathor-wallet-headless/node_modules/@hathor/wallet-lib/lib/websocket.js:180:10)
    at WebSocket.ws.onmessage (/data2/.htr/minming_wallet/hathor-wallet-headless/node_modules/@hathor/wallet-lib/lib/websocket.js:120:12)
    at WebSocket.onMessage (/data2/.htr/minming_wallet/hathor-wallet-headless/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (node:events:390:28)
    at WebSocket.emit (node:domain:475:12)
    at Receiver.receiverOnMessage (/data2/.htr/minming_wallet/hathor-wallet-headless/node_modules/ws/lib/websocket.js:983:20)
    at Receiver.emit (node:events:390:28)

```

**Comment by pedroferreira1** [comment]
@shop271 are you using a custom `gapLimit` in your headless wallet?

Are you connecting to a public full node?
